# Generated by Django 6.0.5 on 2026-08-18 12:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Glittering Field Academy', max_length=200)),
                ('tagline', models.CharField(default='Academics and Morality', max_length=200)),
                ('slogan', models.CharField(default='Raising Leaders, Building Future', max_length=200)),
                ('address', models.CharField(default='No 5 Yarima Dalhatu Crescent, Berger Paint off Chaza Road, Suleja, Niger State', max_length=255)),
                ('email', models.EmailField(default='gfasuleja@gmail.com', max_length=254)),
                ('phone_numbers', models.CharField(default='08074339109, 08117436216, 07037785655', help_text='Comma-separated list of phone numbers.', max_length=255)),
                ('approvals', models.CharField(default='WAEC, NECO, NBAIS', help_text='Comma-separated list of examination-body approvals.', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school/')),
                ('bank_name', models.CharField(default='Jaiz Bank', max_length=100)),
                ('bank_account_number', models.CharField(default='0015162724', max_length=20)),
                ('bank_account_name', models.CharField(default='Glittering Field Academy', max_length=200)),
                ('current_session', models.CharField(default='2025/2026', max_length=20)),
                ('application_fee', models.DecimalField(decimal_places=2, default=Decimal('2000.00'), max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'School Settings',
                'verbose_name_plural': 'School Settings',
            },
        ),
    ]
