# Generated by Django 6.0.5 on 2026-08-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=20)),
                ('section', models.CharField(help_text='Groups cards within a page, e.g. "why_choose_us", "facilities".', max_length=40)),
                ('icon', models.CharField(default='fa-solid fa-star', help_text='Font Awesome class, e.g. "fa-solid fa-book".', max_length=60)),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['page', 'section', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(editable=False, max_length=60, unique=True)),
                ('page', models.CharField(help_text='Which public page this appears on — for grouping in the console.', max_length=20)),
                ('label', models.CharField(help_text='Human-readable name shown in the console, e.g. "Homepage — Welcome intro".', max_length=150)),
                ('eyebrow', models.CharField(blank=True, max_length=100)),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(blank=True, help_text='One paragraph per line.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['page', 'label'],
            },
        ),
    ]
