# Generated by Django 5.2.4 on 2026-09-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_contentblock_pagesection'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='manual_payment_registration_enabled',
            field=models.BooleanField(default=True, help_text='Lets an admin create an account and activate payment for someone who paid by bank transfer. Turn off once this is no longer needed.'),
        ),
    ]
