# Generated by Django 5.2.4 on 2026-09-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_schoolsettings_manual_payment_registration_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolsettings',
            name='manual_payment_registration_enabled',
            field=models.BooleanField(default=True, help_text='Lets an admin record a bank-transfer payment by hand — application fees and termly school fees alike. Turn off once this is no longer needed.'),
        ),
    ]
