# Generated by Django 6.0.5 on 2026-08-18 13:07

import admissions.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(default=admissions.models.generate_application_number, editable=False, max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('nationality', models.CharField(default='Nigerian', max_length=100)),
                ('state_of_origin', models.CharField(max_length=100)),
                ('lga', models.CharField(max_length=100, verbose_name='Local Government Area')),
                ('parent_name', models.CharField(max_length=150)),
                ('relationship', models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Guardian', 'Guardian')], max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('occupation', models.CharField(blank=True, max_length=150)),
                ('applying_for', models.CharField(choices=[('Creche', 'Creche'), ('Pre-Nursery', 'Pre-Nursery'), ('Nursery 1', 'Nursery 1'), ('Nursery 2', 'Nursery 2'), ('Primary 1', 'Primary 1'), ('Primary 2', 'Primary 2'), ('Primary 3', 'Primary 3'), ('Primary 4', 'Primary 4'), ('Primary 5', 'Primary 5'), ('Primary 6', 'Primary 6'), ('JSS 1', 'JSS 1'), ('JSS 2', 'JSS 2'), ('JSS 3', 'JSS 3'), ('SSS 1', 'SSS 1'), ('SSS 2', 'SSS 2'), ('SSS 3', 'SSS 3')], max_length=20)),
                ('previous_school', models.CharField(blank=True, max_length=200)),
                ('previous_class', models.CharField(blank=True, max_length=50)),
                ('previous_performance', models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Very Good', 'Very Good'), ('Good', 'Good'), ('Fair', 'Fair'), ('First time in school', 'First time in school')], max_length=30)),
                ('passport_photo', models.FileField(blank=True, null=True, upload_to=admissions.models.application_document_path)),
                ('birth_certificate', models.FileField(blank=True, null=True, upload_to=admissions.models.application_document_path)),
                ('previous_result', models.FileField(blank=True, null=True, upload_to=admissions.models.application_document_path)),
                ('other_document', models.FileField(blank=True, null=True, upload_to=admissions.models.application_document_path)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('admitted', 'Admitted')], default='pending', max_length=20)),
                ('is_submitted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(default=admissions.models.generate_invoice_number, editable=False, max_length=30, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('waived', 'Waived')], default='unpaid', max_length=10)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='admissions.application')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=admissions.models.generate_payment_reference, max_length=40, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gateway', models.CharField(choices=[('zainpay', 'ZainPay'), ('manual', 'Manual (Bank Transfer)'), ('waiver', 'Waiver')], default='zainpay', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='pending', max_length=10)),
                ('gateway_reference', models.CharField(blank=True, max_length=100)),
                ('gateway_response', models.JSONField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('receipt_number', models.CharField(blank=True, max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='admissions.applicationinvoice')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_application_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('admitted', 'Admitted')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='admissions.application')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
