"""
Django settings for the Glittering Field Academy School Management System.

Generated by 'django-admin startproject' using Django 6.0.5, then hand-edited.
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# .env holds real/local secrets and is gitignored; .env.example documents the
# variable names with safe placeholder values and is committed. Same pattern
# as the reference makarfi project.
load_dotenv(BASE_DIR / '.env')
load_dotenv(BASE_DIR / '.env.example', override=False)

# ── Core ──────────────────────────────────────────────────────────────────────

SECRET_KEY = os.getenv(
    'SECRET_KEY',
    'django-insecure--=2jybdnb-*$+oshp^hub))22nv3(2rxm0w+^mp_r15%fq&)w$',
)

DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [h.strip() for h in os.getenv('ALLOWED_HOSTS', '*').split(',') if h.strip()]

# Public base URL — used to build absolute links in contexts with no request
# object (management commands, server-to-server webhooks, emails).
SITE_URL = os.getenv('SITE_URL', 'http://127.0.0.1:8000').rstrip('/')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',

    # Glittering Field Academy apps
    'accounts',
    'website',
    'admissions',
    'payments',
    'academics',
    'students',
    'staff',
    'attendance',
    'results',
    'examinations',
    'finance',
    'communication',
    'portal',
    'admin_console',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'website.context_processors.school_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Africa/Lagos'
USE_I18N = True
USE_TZ = True


# Static & media files
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
# Serve straight from STATICFILES_DIRS via the finders in dev, so
# WhiteNoise doesn't require a collectstatic-populated STATIC_ROOT to exist.
# Deployment should turn this off and run collectstatic instead.
WHITENOISE_USE_FINDERS = DEBUG
WHITENOISE_AUTOREFRESH = DEBUG
# The frontend prototype's CSS/JS/images already live in assets/ at the repo
# root — served as-is rather than moved, so the existing templates' relative
# {% static %} references keep working unchanged.
STATICFILES_DIRS = [BASE_DIR / 'assets']
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    # Compresses on collectstatic but, unlike CompressedManifestStaticFilesStorage,
    # doesn't require a manifest file to resolve {% static %} tags — so dev/test
    # runs work without a collectstatic step. Deployment can switch to the
    # manifest (cache-busting) variant once collectstatic is part of the deploy.
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ── Auth ──────────────────────────────────────────────────────────────────────

AUTH_USER_MODEL = 'accounts.User'

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/portal/'
LOGOUT_REDIRECT_URL = '/'


# ── ZainPay ───────────────────────────────────────────────────────────────────
# Same variable names as the reference makarfi project
# (C:\Users\ismai\OneDrive\Desktop\Projects2026\makarfi\DjangoApp\settings.py)
# so the ported payment_service.py needs no changes — only new values, from a
# Zainpay zainbox created specifically for Glittering Field Academy.

# JWT from the ZainPay merchant dashboard — Bearer token for API calls.
ZAINPAY_PUBLIC_KEY = os.getenv('ZAINPAY_PUBLIC_KEY', '')
ZAINPAY_ZAINBOX_CODE = os.getenv('ZAINPAY_ZAINBOX_CODE', '')
# Sandbox: https://sandbox.zainpay.ng  |  Live: https://api.zainpay.ng
ZAINPAY_BASE_URL = os.getenv('ZAINPAY_BASE_URL', 'https://sandbox.zainpay.ng')
ZAINPAY_CALLBACK_URL = os.getenv('ZAINPAY_CALLBACK_URL', '')
# Verifies the Zainpay-Signature HMAC-SHA256 header on incoming webhooks.
ZAINPAY_SECRET_KEY = os.getenv('ZAINPAY_SECRET_KEY', '')
# Lookback window (hours) for the reconcile_zainpay management command.
ZAINPAY_RECONCILE_LOOKBACK_HOURS = int(os.getenv('ZAINPAY_RECONCILE_LOOKBACK_HOURS', '720'))


# ── Email ─────────────────────────────────────────────────────────────────────
# Same configuration shape as the reference giia project
# (C:\Users\ismai\OneDrive\Documents\GitHub\giia\DjangoApp\settings.py):
# Gmail SMTP with an app password (never the real account password), values
# only ever from .env. giia's own .env doesn't have real values checked in
# either — EMAIL_HOST_USER / EMAIL_HOST_PASSWORD need to be filled in here
# to actually send mail; until then, send attempts fail-log (see
# communication/emails.py) rather than breaking the request.
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)
